Add Actions File

diff --git a/.github/actions/deploy-cf-stack/action.yaml b/.github/actions/deploy-cf-stack/action.yaml
--- a/.github/actions/deploy-cf-stack/action.yaml
+++ b/.github/actions/deploy-cf-stack/action.yaml
@@ -68,7 +68,8 @@ runs:
             if [[ -n "$VALUE" && "$VALUE" != "null" ]]; then
               echo "$KEY=$VALUE" >> $GITHUB_OUTPUT
             else
-              echo "⚠️ Warning: OutputKey '$KEY' not found in stack outputs." >&2
+          #    echo "⚠️ Warning: OutputKey '$KEY' not found in stack outputs." >&2
+              echo "Warning: OutputKey '$KEY' not found in stack outputs." >&2
             fi
           done
         fi
